const types = {
  SAVE_LOGIN: 'SAVE_LOGIN',
  CURRENCIES_REQUEST: 'CURRENCIES_REQUEST',
  CURRENCIES_REQUEST_FAILED: 'CURRENCIES_REQUEST_FAILED',
  CURRENCIES_REQUEST_SUCCEED: 'CURRENCIES_REQUEST_SUCCEED',
  SEND_NEW_EXPENSE_DATA: 'SEND_NEW_EXPENSE_DATA',
  SEND_NEW_EXPENSE_DATA_FAILED: 'SEND_NEW_EXPENSE_DATA_FAILED',
  SEND_NEW_EXPENSE_DATA_SUCCEED: 'SEND_NEW_EXPENSE_DATA_SUCCEED',
};

export default types;
