const types = {
  SAVE_LOGIN: 'SAVE_LOGIN',
  CURRENCIES_REQUEST: 'CURRENCIES_REQUEST',
  CURRENCIES_REQUEST_FAILED: 'CURRENCIES_REQUEST_FAILED',
  CURRENCIES_REQUEST_SUCCEED: 'CURRENCIES_REQUEST_SUCCEED',
};

export default types;
