const types = {
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  TESTE: 'TESTE',
  REQUEST_SUCCES: 'REQUEST_SUCCES:',
  RECIVE_SUCCES: 'RECIVE_SUCCES',
  RECIVE_FAIL: 'RECIVE_FAIL',
  ADD_EXPENSES: 'ADD_EXPENSES',
  DELETE_EXPENSES: 'DELETE_EXPENSES',
};

export default types;
