const LOGIN_USER = 'LOGIN_USER';
const REQUEST = 'REQUEST';
const REQUEST_SUCESS = 'REQUEST_SUCESS';
const REQUEST_FAILED = 'REQUEST_FAILED';
const ADD_EXPENSE = 'ADD_EXPENSE';
const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
const UPDATE_TOTAL_EXPENSES = 'UPDATE_TOTAL_EXPENSES';

export {
  LOGIN_USER,
  REQUEST,
  REQUEST_SUCESS,
  REQUEST_FAILED,
  ADD_EXPENSE,
  REMOVE_EXPENSE,
  UPDATE_TOTAL_EXPENSES,
};
